### ISSUE TITLE
Ability to pass connectionData to generateToken() method

### ISSUE THREAD

**Issue by bsstoner** [bsstoner/opentok#1]
This functionality is missing in the node.js server side lib and needs to be added.

Thanks to @lucidrains for pointing it out.

**Comment by bsstoner** [comment]
Just pushed new version, this should be fixed now.

**Comment by lucidrains** [comment]
Oh sweet, thanks!

On Jul 27, 2011 12:23 PM, "bsstoner" <
reply@reply.github.com>
wrote:

Just pushed new version, this should be fixed now.

##
